# Generated by Django 5.0.2 on 2024-03-03 23:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('password', models.CharField(default='123456', max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('howDidYouHear', models.CharField(max_length=100, null=True)),
                ('additionalComments', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('password', models.CharField(default='123456', max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('onBoardingDate', models.DateField(null=True, verbose_name='Date Onboarded')),
                ('description', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Session')),
                ('time', models.TimeField(verbose_name='Time of Session')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(1.5)], verbose_name='Duration of Session (Hours)')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Further Description of Student Needs')),
                ('gradeLevel', models.CharField(max_length=100)),
                ('preferredPlatform', models.CharField(default='Zoom', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_student.student')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_student.tutor')),
            ],
        ),
    ]
