# Generated by Django 5.0.2 on 2024-02-29 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('howDidYouHear', models.CharField(max_length=100)),
                ('additionalComments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15)),
                ('onBoardingDate', models.DateField(verbose_name='Date Onboarded')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Session')),
                ('time', models.TimeField(verbose_name='Time of Session')),
                ('duration', models.DurationField(verbose_name='Duration of Session')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Further Description of Student Needs')),
                ('gradeLevel', models.CharField(max_length=100)),
                ('preferredPlatform', models.CharField(default='Zoom', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_student.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_student.tutor')),
            ],
        ),
    ]
