# Generated by Django 5.0.2 on 2024-02-29 22:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additionalComments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='howDidYouHear',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='onBoardingDate',
            field=models.DateField(null=True, verbose_name='Date Onboarded'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=3660))], verbose_name='Duration of Session'),
        ),
    ]
