# Generated by Django 5.0.3 on 2024-03-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_student", "0003_tutoringsession_isrecurring_recurringsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringsession",
            name="sessions",
            field=models.ManyToManyField(to="tutoring_student.tutoringsession"),
        ),
    ]
