# Generated by Django 5.0.2 on 2024-03-01 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_student', '0003_alter_tutoringsession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoring_student.tutor'),
        ),
    ]
