# Generated by Django 5.0.3 on 2024-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_student", "0004_recurringsession_sessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringsession",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, default=[], to="tutoring_student.tutoringsession"
            ),
        ),
    ]
