# Generated by Django 5.0.2 on 2024-03-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_student', '0004_alter_tutoringsession_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
