# Generated by Django 5.0.3 on 2024-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_student", "0005_alter_recurringsession_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="officeHoursHours",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
