# Generated by Django 5.0.3 on 2024-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_student", "0006_tutor_officehourshours"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="officeHoursToday",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
