# Generated by Django 5.0.3 on 2024-04-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoring_student", "0008_alter_tutor_officehourstoday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor",
            old_name="officeHoursToday",
            new_name="officeHoursDate",
        ),
    ]
